version: '3.9'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "9999:9999"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
    restart: always

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}