version: '3.9'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "9999:9999"
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PW}
    restart: always

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PW}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PW}
    ports:
      - "3306:3306"